version: '3'

services:

    frontend:
        image: frontend
        build: ./frontend
        environment: 
            - API_URL=/api

    backend: 
        image: backend
        build: ./backend
        environment: 
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
            - DB_NAME=message_db
            - DB_HOST=db
            - REDIS=redis
            - FRONT_URL=frontend

    redis:
        image: redis:latest

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - ./database/:/var/lib/postgresql/data
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=message_db
            - PGDATA=/var/lib/postgresql/data/pgdata
            
