version: '3'

services:

    frontend:
        image: frontend
        build: ../../Part1/1.12/frontend

    backend: 
        image: backend
        build: ../../Part1/1.12/backend
        environment: 
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
            - DB_NAME=message_db
            - DB_HOST=db
            - REDIS=redis

    redis:
        image: redis:latest

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    db:
        image: postgres:latest
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=message_db
            
