FROM ubuntu:16.04

WORKDIR /builder

COPY . .

RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable" && \
    apt-get update && \
    apt-get install -y docker-ce-cli

ENV REPOSITORY=
ENV IMAGE_NAME=
ENV TAG_NAME=
ENV DOCKER_USERNAME=
ENV DOCKER_PASSWORD=

CMD ["./github-publish.sh"]