version: '3'

services: 
    frontend:
        image: frontend
        build: ../../Part1/1.12/frontend
        ports: 
            - 80:5000

    backend:
        image: backend
        build: ../../Part1/1.12/backend
        ports: 
            - 8000:8000