version: '3'

services: 
    frontend:
        build: ./ml-kurkkumopo-frontend
        container_name: frontend
        ports: 
            - 3000:3000
    backend:
        build: ./ml-kurkkumopo-backend
        container_name: backend
        depends_on:
            - training
        volumes: 
            - model:/src/model
        ports:
            - 5000:5000
    training:
        build: ./ml-kurkkumopo-training
        container_name: training
        volumes: 
            - images:/src/imgs
            - data:/src/data
            - model:/src/model

volumes: 
    images:
    data:
    model: