version: '3'

services:

    frontend:
        image: frontend
        build: ../../Part1/1.12/frontend
        ports: 
            - 80:5000

    backend: 
        image: backend
        build: ../../Part1/1.12/backend
        ports:
            - 8000:8000
        environment: 
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
            - DB_NAME=message_db
            - DB_HOST=db
            - REDIS=redis

    redis:
        image: redis:latest

    db:
        image: postgres:latest
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=message_db
            
